name: 'Checkout Repository'
description: 'Checkout the repository content'
inputs:
  repo-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository content'
      run: git clone https://github.com/${{ github.repository }} .
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
